name: Eleventy Build on Contentful Publish Event

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  deploy:
    name: Build and Upload to S3
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js with the latest LTS version and enable dependency caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Cache npm dependencies to speed up installs in future runs
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies using a clean install
      - name: Install Dependencies
        run: npm ci

      # Debugging: Check if Contentful secrets are available
      - name: Debug Environment Variables
        run: |
          if [ -z "${{ secrets.CTFL_SPACE }}" ]; then echo "❌ CTFL_SPACE is NOT set"; exit 1; fi
          if [ -z "${{ secrets.CTFL_ACCESSTOKEN }}" ]; then echo "❌ CTFL_ACCESSTOKEN is NOT set"; exit 1; fi
          echo "✅ All required environment variables are set"

      # Build the Eleventy site
      - name: Build Site
        run: npm run build
        env:
          CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
          CTFL_ACCESSTOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}

      # Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::588624181414:role/GitHubActionsS3Role
          aws-region: us-east-1  # Change to your AWS region

      # Upload static files to S3
      - name: Upload to S3
        run: |
          aws s3 sync ./_site s3://contentful-static-site/ --delete

      # Deploy the built site to GitHub Pages (use github_token instead of deploy_key)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: gallery.contentful.com
