name: Eleventy Build on Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js with the latest LTS version and enable dependency caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm' # Automatically caches dependencies based on package-lock.json

      # Cache npm dependencies to speed up installs in future runs
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies using a clean install
      - name: Install Dependencies
        run: npm ci

      # Build the Eleventy site
      - name: Build Site
        run: npm run build

      # Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: _site # The output directory of Eleventy
